import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

import logoUrl from "../../assets/icons/logo.svg";


const loadLogo = async (url) => {

    return new Promise((resolve, reject) => {

        const img = new Image();

        img.onload = () => {

            const canvas =
                document.createElement("canvas");

            canvas.width =
                img.naturalWidth;

            canvas.height =
                img.naturalHeight;

            const ctx =
                canvas.getContext("2d");

            ctx.drawImage(
                img,
                0,
                0
            );

            resolve(
                canvas.toDataURL("image/png")
            );

        };

        img.onerror = reject;

        img.src = url;

    });

};


export const exportTablePdf = async ({
    title = "Report",
    subtitle = "",
    columns = [],
    data = [],
    filters = [],
    totalRecords = 0,
    generatedBy = "System",
}) => {

    const doc = new jsPDF(
        "landscape",
        "mm",
        "a4"
    );


    const pageWidth =
        doc.internal.pageSize.getWidth();

    const pageHeight =
        doc.internal.pageSize.getHeight();


    const margin = 14;


    /* =========================================
       LOGO
    ========================================= */

    let logo = null;

    try {

        logo =
            await loadLogo(
                logoUrl
            );

    } catch (error) {

        console.error(
            "Logo loading failed:",
            error
        );

    }


    if (logo) {

        doc.addImage(
            logo,
            "PNG",
            margin,
            12,
            42,
            18
        );

    }


    /* =========================================
       TITLE
    ========================================= */

    doc.setFont(
        "helvetica",
        "bold"
    );

    doc.setFontSize(
        16
    );

    doc.setTextColor(
        20,
        50,
        100
    );

    doc.text(
        title,
        margin + 50,
        19
    );


    /* =========================================
       SUBTITLE
    ========================================= */

    if (subtitle) {

        doc.setFont(
            "helvetica",
            "normal"
        );

        doc.setFontSize(
            8
        );

        doc.setTextColor(
            100,
            100,
            100
        );

        doc.text(
            subtitle,
            margin + 50,
            25
        );

    }


    /* =========================================
       GENERATED DETAILS
    ========================================= */

    const generatedDate =
        new Date().toLocaleString(
            "en-GB",
            {
                day: "2-digit",
                month: "2-digit",
                year: "numeric",
                hour: "2-digit",
                minute: "2-digit",
                hour12: true
            }
        );


    doc.setFontSize(
        7
    );

    doc.setTextColor(
        90,
        90,
        90
    );


    doc.text(
        `Generated On : ${generatedDate}`,
        pageWidth - margin,
        16,
        {
            align: "right"
        }
    );


    doc.text(
        `Generated By : ${generatedBy}`,
        pageWidth - margin,
        22,
        {
            align: "right"
        }
    );


    /* =========================================
       LINE
    ========================================= */

    doc.setDrawColor(
        13,
        110,
        253
    );

    doc.setLineWidth(
        0.5
    );

    doc.line(
        margin,
        32,
        pageWidth - margin,
        32
    );


    /* =========================================
       FILTERS
    ========================================= */

    const activeFilters =
        filters.filter(
            filter =>
                filter.value !== undefined &&
                filter.value !== null &&
                String(
                    filter.value
                ).trim() !== ""
        );


    let startY = 42;


    if (
        activeFilters.length > 0
    ) {

        doc.setFont(
            "helvetica",
            "bold"
        );

        doc.setFontSize(
            8
        );

        doc.setTextColor(
            20,
            50,
            100
        );


        doc.text(
            "FILTERS APPLIED",
            margin,
            startY
        );


        startY += 6;


        activeFilters.forEach(
            (filter, index) => {

                const x =
                    margin +
                    index * 70;


                doc.setFont(
                    "helvetica",
                    "bold"
                );

                doc.setFontSize(
                    7
                );

                doc.setTextColor(
                    90,
                    90,
                    90
                );


                doc.text(
                    `${filter.label}:`,
                    x,
                    startY
                );


                doc.setFont(
                    "helvetica",
                    "normal"
                );

                doc.setTextColor(
                    40,
                    40,
                    40
                );


                doc.text(
                    String(
                        filter.value
                    ),
                    x + 25,
                    startY
                );

            }
        );


        startY += 8;

    }


    /* =========================================
       TOTAL
    ========================================= */

    doc.setFont(
        "helvetica",
        "bold"
    );

    doc.setFontSize(
        8
    );

    doc.setTextColor(
        90,
        90,
        90
    );


    doc.text(
        `Total Records : ${totalRecords}`,
        pageWidth - margin,
        startY,
        {
            align: "right"
        }
    );


    startY += 8;


    /* =========================================
       TABLE
    ========================================= */

    const headers =
        columns.map(
            column =>
                column.label
        );


    const rows =
        data.map(
            (row, index) => {

                return columns.map(
                    column => {

                        if (
                            column.renderPdf
                        ) {

                            return column.renderPdf(
                                row,
                                index
                            );

                        }

                        return (
                            row[
                                column.key
                            ] ?? ""
                        );

                    }
                );

            }
        );


    autoTable(
        doc,
        {

            startY,

            head: [
                headers
            ],

            body: rows,

            margin: {
                left: margin,
                right: margin,
                bottom: 18
            },

            theme: "grid",

            styles: {
                font: "helvetica",
                fontSize: 8,
                cellPadding: 3,
                valign: "middle"
            },

            headStyles: {
                fillColor: [
                    20,
                    55,
                    100
                ],
                textColor: [
                    255,
                    255,
                    255
                ],
                fontStyle: "bold",
                halign: "center"
            },

            alternateRowStyles: {
                fillColor: [
                    248,
                    248,
                    248
                ]
            },

            didDrawPage: () => {

                const page =
                    doc.internal.getNumberOfPages();


                doc.setFontSize(
                    7
                );

                doc.setTextColor(
                    100,
                    100,
                    100
                );


                doc.text(
                    "NeoEHS",
                    margin,
                    pageHeight - 7
                );


                doc.text(
                    `Page ${page}`,
                    pageWidth - margin,
                    pageHeight - 7,
                    {
                        align: "right"
                    }
                );

            }

        }
    );


    /* =========================================
       FILE NAME
    ========================================= */

    const fileName =
        title
            .replace(
                /[^a-zA-Z0-9]/g,
                "_"
            );


    doc.save(
        `${fileName}.pdf`
    );

};